#!/usr/bin/env tsx
/**
 * generate-prompts.ts
 *
 * Reads the canonical role prompts in prompts/agents/*.md and emits, deterministically:
 *   1. src/shared/generated-prompts.ts — committed TS module the Pi runtime imports.
 *   2. integrations/claude-code/agents/<role>.md — native Claude Code subagent definitions.
 *
 * The canonical Markdown files are the single source of truth for each role prompt body.
 * Run `npm run generate` after editing any canonical prompt; `npm run check:generated`
 * (part of `npm run build`) fails if the committed outputs are stale.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { isMainModule } from "../src/shared/is-main-module.js";

export const ROLES = ["finder", "oracle", "librarian", "worker", "manager"] as const;
export type Role = (typeof ROLES)[number];

// Frontmatter keys emitted into Claude agent files, in this fixed order (determinism).
const AGENT_FRONTMATTER_KEYS = ["name", "description", "tools", "model"] as const;

export interface CanonicalPrompt {
  role: Role;
  frontmatter: Record<string, string>;
  body: string;
}

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(scriptDir, "..");
const agentsDir = join(repoRoot, "prompts", "agents");
const generatedTsPath = join(repoRoot, "src", "shared", "generated-prompts.ts");
const claudeAgentsDir = join(repoRoot, "integrations", "claude-code", "agents");

export interface Frontmatter {
  frontmatter: Record<string, string>;
  body: string;
}

/**
 * Parse a `---`-delimited frontmatter block (flat `key: value` pairs) plus the
 * Markdown body that follows. `label` names the source in error messages. Shared
 * by the generator and its tests so both read frontmatter the same way.
 */
export function parseFrontmatter(raw: string, label: string): Frontmatter {
  const match = raw.replace(/\r\n/g, "\n").match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!match) throw new Error(`${label} is missing a YAML frontmatter block`);
  const [, fmBlock, rest] = match;
  const frontmatter: Record<string, string> = {};
  for (const line of fmBlock.split("\n")) {
    if (!line.trim()) continue;
    const idx = line.indexOf(":");
    if (idx === -1) throw new Error(`Malformed frontmatter line in ${label}: ${line}`);
    frontmatter[line.slice(0, idx).trim()] = line.slice(idx + 1).trim();
  }
  return { frontmatter, body: rest };
}

export function parseCanonical(role: Role, baseDir: string = agentsDir): CanonicalPrompt {
  const raw = readFileSync(join(baseDir, `${role}.md`), "utf-8");
  const { frontmatter, body } = parseFrontmatter(raw, `prompts/agents/${role}.md`);
  if (frontmatter.name !== role) {
    throw new Error(`prompts/agents/${role}.md declares name "${frontmatter.name}", expected "${role}"`);
  }
  return { role, frontmatter, body: body.trim() };
}

export function constName(role: Role): string {
  return `${role.toUpperCase()}_CANONICAL`;
}

export function renderGeneratedTs(prompts: CanonicalPrompt[]): string {
  const header = [
    "// This file is generated by scripts/generate-prompts.ts. Do not edit directly.",
    "// Source: prompts/agents/*.md — run `npm run generate` to refresh.",
    "",
  ].join("\n");
  const consts = prompts
    .map((p) => `export const ${constName(p.role)} = ${JSON.stringify(p.body)};`)
    .join("\n\n");
  return `${header}\n${consts}\n`;
}

export function renderClaudeAgent(prompt: CanonicalPrompt): string {
  const fm = AGENT_FRONTMATTER_KEYS.map((key) => {
    const value = prompt.frontmatter[key];
    if (value === undefined) throw new Error(`prompts/agents/${prompt.role}.md missing frontmatter key "${key}"`);
    return `${key}: ${value}`;
  }).join("\n");
  return `---\n${fm}\n---\n\n${prompt.body}\n`;
}

export function generate(): void {
  const prompts = ROLES.map((role) => parseCanonical(role));

  if (!existsSync(dirname(generatedTsPath))) mkdirSync(dirname(generatedTsPath), { recursive: true });
  writeFileSync(generatedTsPath, renderGeneratedTs(prompts), "utf-8");

  if (!existsSync(claudeAgentsDir)) mkdirSync(claudeAgentsDir, { recursive: true });
  for (const prompt of prompts) {
    writeFileSync(join(claudeAgentsDir, `${prompt.role}.md`), renderClaudeAgent(prompt), "utf-8");
  }

  console.log(
    `Generated ${generatedTsPath} and ${prompts.length} Claude agent files in ${claudeAgentsDir}`,
  );
}

if (isMainModule(import.meta.url)) generate();
